services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: doc-mind-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docmind
    ports:
      - "5434:5432"
    volumes:

      - ytpgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  ytpgdata: